import type { LanguageCode } from "@/lib/types";
import { FREQUENCY_META, type FrequencyMeta } from "./manifest";

export { FREQUENCY_META };
export type { FrequencyMeta };

/**
 * The real corpus frequency lists.
 *
 * These are not hand-authored: each one is the token frequency of a real
 * corpus, cleaned of punctuation, numerals and cross-language bleed. They are
 * what makes the product's central claim — "the words that matter", "the top
 * 100 words" — a statement about the language rather than about our seed file.
 *
 * The lists are ~3,000 entries each, so they live in one module per language
 * and are loaded on demand. Nothing imports them eagerly; `FREQUENCY_META` is
 * the small synchronous half that the UI needs for a denominator or a source
 * line.
 *
 * Generated by `.workbuddy-ai/freq/build_freq.py`.
 */

export interface FrequencyEntry {
  word: string;
  /** 1-based position in the list. 1 = most frequent. */
  rank: number;
  /** Raw occurrences in the corpus, or null when the source publishes none. */
  count: number | null;
}

const CACHE = new Map<LanguageCode, FrequencyEntry[]>();

/* Explicit map rather than a computed import path: the bundler needs to see
   every specifier statically to split them into separate chunks. */
const LOADERS: Record<LanguageCode, () => Promise<{ FREQ: string }>> = {
  ja: () => import("./ja"),
  ko: () => import("./ko"),
  zh: () => import("./zh"),
  es: () => import("./es"),
  fr: () => import("./fr"),
  de: () => import("./de"),
  ne: () => import("./ne"),
  hi: () => import("./hi"),
  ar: () => import("./ar"),
  ru: () => import("./ru"),
};

function parse(payload: string): FrequencyEntry[] {
  const out: FrequencyEntry[] = [];
  let rank = 0;
  for (const line of payload.split("\n")) {
    if (!line) continue;
    // Two shapes: `"word count"` and, for rank-only sources, a bare word.
    const at = line.lastIndexOf(" ");
    const tail = at === -1 ? "" : line.slice(at + 1);
    const hasCount = at !== -1 && tail !== "" && Number.isFinite(Number(tail));
    const word = hasCount ? line.slice(0, at) : line;
    if (!word) continue;
    out.push({ word, rank: ++rank, count: hasCount ? Number(tail) : null });
  }
  return out;
}

/** The whole list for a language, parsed once and cached for the session. */
export async function loadFrequencyList(language: LanguageCode): Promise<FrequencyEntry[]> {
  const cached = CACHE.get(language);
  if (cached) return cached;
  const mod = await LOADERS[language]();
  const parsed = parse(mod.FREQ);
  CACHE.set(language, parsed);
  return parsed;
}

/** Entries in the shipped list. Synchronous, for denominators. */
export function frequencyListSize(language: LanguageCode): number {
  return FREQUENCY_META[language]?.size ?? 0;
}

export function frequencySource(language: LanguageCode): FrequencyMeta | undefined {
  return FREQUENCY_META[language];
}

/** Where a word sits in the corpus, or null when the list does not contain it. */
export async function frequencyRankOf(
  language: LanguageCode,
  word: string,
): Promise<number | null> {
  const list = await loadFrequencyList(language);
  const hit = list.find((e) => e.word === word);
  return hit ? hit.rank : null;
}

/**
 * The next `count` entries at or after `rank` — the honest answer to "what am
 * I marching towards". Skips anything already passed.
 */
export async function frequencySlice(
  language: LanguageCode,
  fromRank: number,
  count: number,
): Promise<FrequencyEntry[]> {
  const list = await loadFrequencyList(language);
  return list.slice(Math.max(0, fromRank - 1), Math.max(0, fromRank - 1) + count);
}

/**
 * The share of every token in the corpus that the most frequent `topN` words
 * account for — the product's central claim, computed rather than asserted.
 *
 * Both halves of the fraction come from the same list the app teaches from:
 * the numerator is the summed occurrence count of the slice, the denominator is
 * the corpus total recorded when the list was built. Nothing here is estimated.
 *
 * Returns null for a rank-only source (Japanese), because a percentage we
 * cannot compute is worse than no percentage at all.
 */
export async function frequencyCoverage(
  language: LanguageCode,
  topN: number,
): Promise<number | null> {
  const meta = FREQUENCY_META[language];
  if (!meta?.hasCounts) return null;
  const list = await loadFrequencyList(language);
  const covered = list.slice(0, topN).reduce((sum, e) => sum + (e.count ?? 0), 0);
  const total = meta.totalTokens ?? list.reduce((sum, e) => sum + (e.count ?? 0), 0);
  return total > 0 ? covered / total : null;
}

/**
 * A handful of real entries from the list, for showing what is coming rather
 * than describing it.
 *
 * There is deliberately no length filter. An earlier version dropped tokens of
 * a single character to avoid the odd stray letter a raw token list carries —
 * but `clean_token` already rejects anything that is not a word (no digits, no
 * punctuation, must be in the language's own script), so what survives at one
 * character is a real one-character word. The filter only ever fired on
 * Chinese and Japanese, where single characters are ordinary words, and left
 * the panel showing three chips for Chinese where every other language showed
 * six. Filtering also contradicts the panel's own copy, which promises the
 * actual next entries in the ranking.
 */
export async function frequencySample(
  language: LanguageCode,
  fromRank: number,
  count: number,
): Promise<FrequencyEntry[]> {
  return frequencySlice(language, fromRank, count);
}
