import type { LanguageCode } from "@/lib/types";

/**
 * The synchronous face of the frequency lists: sizes and provenance only.
 *
 * The lists themselves are ~3,000 entries per language and live in one module
 * each, so they can be code-split — nothing imports them eagerly. This manifest
 * is what the UI needs synchronously (a denominator, a source line), and it is
 * small enough to sit in the main bundle without regret.
 *
 * GENERATED by .workbuddy-ai/freq/build_freq.py — do not hand-edit.
 */
export interface FrequencyMeta {
  /** Entries in the shipped list. */
  size: number;
  /** Tokens the corpus was counted over. Null when the source publishes no counts. */
  totalTokens: number | null;
  /** Distinct tokens seen before the top-N cut. Null when counts are unavailable. */
  distinctTokens: number | null;
  /** False for rank-only sources (wordfreq). */
  hasCounts: boolean;
  source: string;
  url: string;
  licence: string;
  file: string;
}

/**
 * Provenance for the languages that have a corpus list.
 *
 * Keyed by the spoken languages only, and partial on purpose: a signed language
 * has no frequency list, so there is nothing to describe. Declaring it as
 * `Record<LanguageCode, …>` would force a fabricated entry — a size of 0 and a
 * made-up source — into a file the build generates and nobody reads.
 */
export const FREQUENCY_META: Partial<Record<LanguageCode, FrequencyMeta>> = {
  ja: {
    size: 3000,
    totalTokens: null,
    distinctTokens: null,
    hasCounts: false,
    source: "wordfreq 3.x (word-level; see repo for underlying sources)",
    url: "https://github.com/rspeer/wordfreq",
    licence: "see repository",
    file: "wordfreq:ja",
  },
  ko: {
    size: 3000,
    totalTokens: 5163940,
    distinctTokens: 49406,
    hasCounts: true,
    source: "hermitdave/FrequencyWords 2018 (OpenSubtitles)",
    url: "https://github.com/hermitdave/FrequencyWords",
    licence: "CC BY-SA 4.0",
    file: "ko_50k.txt",
  },
  zh: {
    size: 3000,
    totalTokens: 74700983,
    distinctTokens: 42911,
    hasCounts: true,
    source: "hermitdave/FrequencyWords 2018 (OpenSubtitles)",
    url: "https://github.com/hermitdave/FrequencyWords",
    licence: "CC BY-SA 4.0",
    file: "zh_50k.txt",
  },
  es: {
    size: 3000,
    totalTokens: 412403261,
    distinctTokens: 49788,
    hasCounts: true,
    source: "hermitdave/FrequencyWords 2018 (OpenSubtitles)",
    url: "https://github.com/hermitdave/FrequencyWords",
    licence: "CC BY-SA 4.0",
    file: "es_50k.txt",
  },
  fr: {
    size: 3000,
    totalTokens: 290314117,
    distinctTokens: 49493,
    hasCounts: true,
    source: "hermitdave/FrequencyWords 2018 (OpenSubtitles)",
    url: "https://github.com/hermitdave/FrequencyWords",
    licence: "CC BY-SA 4.0",
    file: "fr_50k.txt",
  },
  de: {
    size: 3000,
    totalTokens: 151385359,
    distinctTokens: 49729,
    hasCounts: true,
    source: "hermitdave/FrequencyWords 2018 (OpenSubtitles)",
    url: "https://github.com/hermitdave/FrequencyWords",
    licence: "CC BY-SA 4.0",
    file: "de_50k.txt",
  },
  ne: {
    size: 3000,
    totalTokens: 2731250,
    distinctTokens: 79459,
    hasCounts: true,
    source: "Someman/news_nepali (Hugging Face), counted from the corpus",
    url: "https://huggingface.co/datasets/Someman/news_nepali",
    licence: "see dataset card",
    file: "nep_news_train.parquet",
  },
  hi: {
    size: 3000,
    totalTokens: 712364,
    distinctTokens: 20613,
    hasCounts: true,
    source: "hermitdave/FrequencyWords 2018 (OpenSubtitles)",
    url: "https://github.com/hermitdave/FrequencyWords",
    licence: "CC BY-SA 4.0",
    file: "hi_full.txt",
  },
  ar: {
    size: 3000,
    totalTokens: 148302653,
    distinctTokens: 49194,
    hasCounts: true,
    source: "hermitdave/FrequencyWords 2018 (OpenSubtitles)",
    url: "https://github.com/hermitdave/FrequencyWords",
    licence: "CC BY-SA 4.0",
    file: "ar_50k.txt",
  },
  ru: {
    size: 3000,
    totalTokens: 144139672,
    distinctTokens: 49055,
    hasCounts: true,
    source: "hermitdave/FrequencyWords 2018 (OpenSubtitles)",
    url: "https://github.com/hermitdave/FrequencyWords",
    licence: "CC BY-SA 4.0",
    file: "ru_50k.txt",
  },
};
