/**
 * The classifier: a small multi-layer perceptron over hand features.
 *
 * The weights are not trained here and not fetched from anyone; they are
 * generated by `scripts/train-sign-model.ts` from the handshapes the app
 * already ships in `data/asl.ts`, and committed as `model.json`. That keeps the
 * whole recogniser ours, offline, and free of any per-request cost.
 *
 * A hand is small: the input is 20 numbers and there are under three thousand
 * weights, so a forward pass is a few thousand multiplies — nothing next to
 * the cost of the landmark model that produced the features.
 */

import type { HandFeatures } from "@/lib/sign/features";

/** One fully-connected layer. `w[j][i]` weights input i into output j. */
export interface MLPLayer {
  w: number[][];
  b: number[];
}

export interface SignModel {
  version: number;
  /** Input length. Must equal `FEATURE_DIM`. */
  featureDim: number;
  /** Hidden layer widths, e.g. [64, 32]. */
  hidden: number[];
  /** Output letters, in the order the softmax emits them. */
  classes: string[];
  /** Per-feature standardisation, learned from the training set. */
  mean: number[];
  std: number[];
  layers: MLPLayer[];
}

/** Below this top probability the frame is reported as "no clear letter". */
export const CONFIDENCE_THRESHOLD = 0.55;

/** Served from `public/`. Fetched once and cached in module scope. */
export const MODEL_URL = "/sign-model.json";

function relu(v: number): number {
  return v > 0 ? v : 0;
}

function softmax(logits: number[]): number[] {
  let max = -Infinity;
  for (const v of logits) if (v > max) max = v;
  const exps = logits.map((v) => Math.exp(v - max));
  const sum = exps.reduce((a, b) => a + b, 0) || 1;
  return exps.map((v) => v / sum);
}

/**
 * Standardise, run the layers, softmax the last one.
 *
 * Exported separately from `classify` so the check script can call it directly
 * with a model it imported, without a network round trip.
 */
export function forward(model: SignModel, values: number[]): number[] {
  if (values.length !== model.featureDim) return [];
  let x = values.map((v, i) => {
    const std = model.std[i] || 1;
    return (v - model.mean[i]) / std;
  });
  for (let layerIndex = 0; layerIndex < model.layers.length; layerIndex++) {
    const { w, b } = model.layers[layerIndex];
    const out = new Array<number>(w.length).fill(0);
    for (let j = 0; j < w.length; j++) {
      let sum = b[j] ?? 0;
      const row = w[j];
      for (let i = 0; i < row.length; i++) sum += row[i] * x[i];
      out[j] = sum;
    }
    x = layerIndex === model.layers.length - 1 ? softmax(out) : out.map(relu);
  }
  return x;
}

export interface Prediction {
  /** `null` when the best letter is below the confidence threshold. */
  letter: string | null;
  confidence: number;
}

/**
 * Classify a frame.
 *
 * A confident wrong letter is worse than an honest "not sure", so a top
 * probability under the threshold is reported as no letter at all. The screen
 * asks the learner to hold the shape; a letter only appears once the model is
 * actually sure of it.
 */
export function classify(model: SignModel, features: HandFeatures | null): Prediction {
  if (!features) return { letter: null, confidence: 0 };
  const probs = forward(model, features.values);
  if (probs.length === 0) return { letter: null, confidence: 0 };
  let best = 0;
  for (let i = 1; i < probs.length; i++) if (probs[i] > probs[best]) best = i;
  const confidence = probs[best];
  return {
    letter: confidence >= CONFIDENCE_THRESHOLD ? model.classes[best] ?? null : null,
    confidence,
  };
}

let cached: Promise<SignModel> | null = null;

/**
 * Load the committed weights once per page.
 *
 * The promise itself is cached, not just the result, so several callers in the
 * same tick share one request rather than racing three.
 */
export function loadSignModel(): Promise<SignModel> {
  if (!cached) {
    cached = fetch(MODEL_URL, { cache: "force-cache" }).then(async (res) => {
      if (!res.ok) throw new Error(`sign model unavailable (${res.status})`);
      return (await res.json()) as SignModel;
    });
    // A failed load must be retryable — a cold offline start should not poison
    // the cache for the rest of the session.
    cached.catch(() => {
      cached = null;
    });
  }
  return cached;
}
