/**
 * The word-sign classifier: one LSTM over hand-feature sequences.
 *
 * The weights are not trained here; they are generated by
 * `scripts/train-word-model.mjs` from SL-derived templates and committed as
 * `word-model.json` — the same plain-weights convention as `model.ts`, so the
 * app itself ships no framework. The LSTM reads the resampled 48×20 sequences
 * `resampleFrames` produces, which is what makes motion (not just held poses)
 * visible to it.
 *
 * Never throws on bad input: degenerate sequences yield no distribution and
 * classify as "no word", so a dropped camera frame degrades to "try again".
 */

import { resampleFrames } from "@/lib/sign/word-dtw";
import type { MLPLayer } from "@/lib/sign/model";

/** LSTM weights. tfjs/Keras gate order: input, forget, cell, output. */
export interface LSTMLayer {
  /** [input][4*units] */
  kernel: number[][];
  /** [units][4*units] */
  recurrent: number[][];
  /** [4*units] */
  bias: number[];
}

export interface WordModel {
  version: number;
  /** Frames per sequence. Must equal `RESAMPLE_LEN`. */
  seqLen: number;
  /** Width of one frame. Must equal `FEATURE_DIM`. */
  featureDim: number;
  lstmUnits: number;
  /** Dense widths after the LSTM, e.g. [32]. */
  hidden: number[];
  /** Pilot glosses, in the order the softmax emits them. */
  classes: string[];
  /** Per-feature standardisation, learned from the training set. */
  mean: number[];
  std: number[];
  lstm: LSTMLayer;
  layers: MLPLayer[];
}

/** Below this top probability the attempt is reported as "no clear word". */
export const WORD_CONFIDENCE_THRESHOLD = 0.5;

/** Served from `public/`. Fetched once and cached in module scope. */
export const WORD_MODEL_URL = "/word-model.json";

function sigmoid(v: number): number {
  return 1 / (1 + Math.exp(-v));
}

function relu(v: number): number {
  return v > 0 ? v : 0;
}

function softmax(logits: number[]): number[] {
  let max = -Infinity;
  for (const v of logits) if (v > max) max = v;
  const exps = logits.map((v) => Math.exp(v - max));
  const sum = exps.reduce((a, b) => a + b, 0) || 1;
  return exps.map((v) => v / sum);
}

function validSequence(model: WordModel, seq: number[][]): boolean {
  if (!Array.isArray(seq) || seq.length === 0) return false;
  return seq.every(
    (f) =>
      Array.isArray(f) &&
      f.length === model.featureDim &&
      f.every((v) => typeof v === "number" && Number.isFinite(v)),
  );
}

/**
 * Standardise, resample, run the LSTM, run the dense layers, softmax.
 *
 * Exported separately from `classifyWord` so the check script can call it
 * directly with a model it built, without a network round trip.
 */
export function wordForward(model: WordModel, seq: number[][]): number[] {
  try {
    if (!validSequence(model, seq)) return [];
    const frames = resampleFrames(seq, model.seqLen).map((f) =>
      f.map((v, i) => {
        const std = model.std[i] || 1;
        return (v - (model.mean[i] ?? 0)) / std;
      }),
    );
    const u = model.lstmUnits;
    const { kernel, recurrent, bias } = model.lstm;
    if (
      kernel.length !== model.featureDim ||
      recurrent.length !== u ||
      bias.length !== 4 * u
    ) {
      return [];
    }
    let h = new Array<number>(u).fill(0);
    let c = new Array<number>(u).fill(0);
    for (const x of frames) {
      const ni = new Array<number>(u);
      const nf = new Array<number>(u);
      const nc = new Array<number>(u);
      const no = new Array<number>(u);
      for (let k = 0; k < u; k++) {
        let gi = bias[k];
        let gf = bias[u + k];
        let gc = bias[2 * u + k];
        let go = bias[3 * u + k];
        for (let d = 0; d < x.length; d++) {
          const row = kernel[d];
          if (!row) continue;
          gi += row[k] * x[d];
          gf += row[u + k] * x[d];
          gc += row[2 * u + k] * x[d];
          go += row[3 * u + k] * x[d];
        }
        for (let j = 0; j < u; j++) {
          const rrow = recurrent[j];
          if (!rrow) continue;
          gi += rrow[k] * h[j];
          gf += rrow[u + k] * h[j];
          gc += rrow[2 * u + k] * h[j];
          go += rrow[3 * u + k] * h[j];
        }
        ni[k] = sigmoid(gi);
        nf[k] = sigmoid(gf);
        nc[k] = Math.tanh(gc);
        no[k] = sigmoid(go);
      }
      const nh = new Array<number>(u);
      for (let k = 0; k < u; k++) {
        c[k] = nf[k] * c[k] + ni[k] * nc[k];
        nh[k] = no[k] * Math.tanh(c[k]);
      }
      h = nh;
    }
    let out = h;
    for (let li = 0; li < model.layers.length; li++) {
      const { w, b } = model.layers[li];
      const next = new Array<number>(w.length).fill(0);
      for (let j = 0; j < w.length; j++) {
        let s = b[j] ?? 0;
        const row = w[j];
        for (let i = 0; i < row.length; i++) s += row[i] * (out[i] ?? 0);
        next[j] = s;
      }
      out = li === model.layers.length - 1 ? softmax(next) : next.map(relu);
    }
    return out;
  } catch {
    return [];
  }
}

export interface WordPrediction {
  /** `null` when the best word is below the confidence threshold. */
  word: string | null;
  confidence: number;
}

/**
 * Classify one attempt.
 *
 * A confident wrong word is worse than an honest "not sure", so a top
 * probability under the threshold is reported as no word at all.
 */
export function classifyWord(model: WordModel, seq: number[][] | null | undefined): WordPrediction {
  if (!seq) return { word: null, confidence: 0 };
  const probs = wordForward(model, seq);
  if (probs.length === 0) return { word: null, confidence: 0 };
  let best = 0;
  for (let i = 1; i < probs.length; i++) if (probs[i] > probs[best]) best = i;
  const confidence = probs[best];
  return {
    word: confidence >= WORD_CONFIDENCE_THRESHOLD ? model.classes[best] ?? null : null,
    confidence,
  };
}

let cached: Promise<WordModel> | null = null;

/**
 * Load the committed word weights once per page.
 *
 * Rejects (rather than resolving null) when no model was ever trained, so
 * the test page can tell "no neural model yet — DTW only" apart from a model
 * that loaded and is unsure. A failed load stays retryable.
 */
export function loadWordModel(): Promise<WordModel> {
  if (!cached) {
    cached = fetch(WORD_MODEL_URL, { cache: "force-cache" }).then(async (res) => {
      if (!res.ok) throw new Error(`word model unavailable (${res.status})`);
      return (await res.json()) as WordModel;
    });
    cached.catch(() => {
      cached = null;
    });
  }
  return cached;
}
